#!/usr/bin/env bash
# fixing the probelms when using docker
#making the apache server return Hello holberton

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start 
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo etc/init.d/apache2 restart 
